### ISSUE TITLE
gradlew check failed! my javasdk is jdk8

### ISSUE THREAD

**Issue by andyyuan78** [brmson/yodaqa#25]
nvy@ub1404envy:~/os_prj/github/_QA/brmson/yodaqa$  ./gradlew check 
Downloading https://services.gradle.org/distributions/gradle-2.1-bin.zip
.........................................................................................................................................................................................................

https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6.pom
Download https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.7.6/jcl-over-slf4j-1.7.6.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-core/4.2.5/httpcomponents-core-4.2.5.pom
Download http://ailao.eu/maven/eu/ailao/gloveDict/1.0-stanford/gloveDict-1.0-stanford.jar
:generateTypeSystem FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateTypeSystem'.
> Could not resolve all dependencies for configuration ':compile'.
   > Could not download artifact 'eu.ailao:gloveDict:1.0-stanford:gloveDict.jar'
      > Failed to download resource 'http://ailao.eu/maven/eu/ailao/gloveDict/1.0-stanford/gloveDict-1.0-stanford.jar'.
         > Premature end of Content-Length delimited message body (expected: 69243072; received: 431535

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 8.85 secs

**Comment by pasky** [comment]
Did that error persist?

**Comment by jbauer180266** [comment]
I think this issue can be closed. It looks very much like a connection error on the user side. I just tested gloveDict and I can obtain it just fine.

@andyyuan78 Have you tried making sure your connection is stable and then just rerunning the build? I'm fairly confident this should fix it.

**Comment by andyyuan78** [comment]
it does repeated, but I noticed that it was a download issue..

thanks all

**Comment by bambamochu** [comment]
How did you fix it? It is a connection issue, I used another machine to download .gradle and got all the files, and uploaded them to
/home/username/.gradle/caches/modules-2/files-2.1/eu.ailao/gloveDict/1.0-stanford/81f816cd79944c228c3da08d706f58afacd6a590/gloveDict-1.0-stanford.jar

But I still get the same issue
